You can get access to the sample project published at GitHub as follows

* link:{REPOS_URL}[kazurayam / Vite-CSS-Module-hashes-HTML-ID-as-well]

== Introduction

I am in charge of managing the homepage of an academic organization. That site is an old-fashioned HTML site and has not been componentized in its source, so maintenance is problematic. I am eager to rewrite this site using JSX in TypeScript. The site is a construct of static HTML, CSS, and JS in the Apache server's htdocs directory, and I want to maintain that simple configuration. I thought that I would be able to migrate the system to a new one using the static site generator [minista](https://github.com/qrac/minista). I learned minista for a weeks, and  published in a Zenn article about how I got started with minista.

* link:{BLOB_URL}/base-project/index.html[スタティックサイトジェネレーター minista を試してみた]

I want the new site to look exactly like the original. That's a requirement. However, when I rewrote the original site using TypeScript + JSX + CSS modules, the new site looked different from the original. There were several reasons, most of which were due to my mistakes. But now, I'm struggling with an incident that seems to be caused by a design failure in Minista itself. I want to report what I found and resolve this issue with the help of @qrac, the originator of minista.

== My question

The official documentation of minista writes about [pluginBundle](https://minista.qranoko.jp/docs/plugins/bundle):

[quote]
____
JSX内でimportしたCSS・画像を出力するプラグイン。
pluginBundle finds CSS and Images imported in JSX, process them, outputs them into the `dist` directory.
____

Alos the documetation about [pluginEntity](https://minista.qranoko.jp/docs/plugins/entry)
    
[quote]
____
ルートパスのCSS・JavaScript・画像をビルドプロセスに乗せるプラグイン。
pluginEntity finds CSS, JavaScript and Images in the src path, bring them into the build processing.
____

The documents tell me that both pluginBundle and pluginEntity process the CSS files. 

But, is it safe to call both of them together in a build? I am afraid, the 2 plugins likely collide each other.

The pluginBundle will generated a bundle css file. But the pluginEntiy may generate another bundle css file, which overwrites the one generated by pluginBundle. Eventually the style of web site breaks. --- This is what happend in my sample project. I will describe my thought in the following sections.